version: 2.1

# 1. Create a .circleci directory
# 2. Create config.yml
# 3. Define jobs
#				- build
#				- tests
#				- linting
#				- build and push docker image
#				- deployement
# 4. Define Workflows
#				- build/test/quality
#				- build/push docker image
#				- deploy on heroku


jobs:
  build-test-linting:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependancies
          command: python install -r requirements.txt
      - run:
          name: run tests
          command: pytest
      - run:
          name: run linting
          command: flake8

  # build and push Docker image
  build_push_docker:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker
      - environment:
          IMAGE_NAME: diddrdv/oclettings
      - run:
          command:
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker built -t $IMAGE_NAME:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:$TAG

workflows:
  build_test_quality:
    jobs:
      - build_test_linting

  dockerize_app:
    jobs:
      - build_push_docker:
          filters:
            branches:
              only: main
#    deploy:
#      jobs:
#        - deploy:
#        filters:
#          branches:
#            only: main