version: 2.1

# 1. Create a .circleci directory
# 2. Create config.yml
# 3. Define jobs
#				- build
#				- tests
#				- linting
#				- build and push docker image
#				- deployement
# 4. Define Workflows
#				- build/test/quality
#				- build/push docker image
#				- deploy on heroku

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build_test_linting:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependancies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: pytest
      - run:
          name: run linting
          command: flake8

  build_push_docker:
    docker:
      - image: cimg/base:2021.11
    environment:
      IMAGE_NAME: diddrdv/oclettings
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $IMAGE_NAME:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:$TAG

#  build_deploy:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Build and push image to Heroku
#          command: |
#            sudo curl https://cli-assets.heroku.com/install.sh | sh
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-v01 web
#            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-v01 web



workflows:
  test_dockerize_deploy_app:
    jobs:
      - build_test_linting
      - build_push_docker:
          requires:
            - build_test_linting
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - build_push_docker
          post-steps:
            - run: heroku run -a oc-lettings-v01 python manage.py migrate
            - run: heroku run -a oc-lettings-v01 python manage.py loaddata data.json
          filters:
            branches:
              only:
                main

#      - build_deploy:
#          requires:
#            - build_push_docker
#          filters:
#            branches:
#              only: main
